import { configApp } from '@configs/app';
import Head from 'next/head';

const MetaHead = () => (
  <Head>
    <title>
      {configApp.APP_NAME} | {configApp.APP_VERSION}
    </title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/icons/favicon.ico" />
  </Head>
);

export default MetaHead;
